#!/usr/bin/env bash
# Simple chatting simulator app
if [ "$#" -ne 1 ]
then
        echo "Usage: $0 host OR $0 client"
        exit 1
elif [ $1 -eq 'host' ]
then
	nc -l -p 54321
elif [[ $1 == 'client' ]] && [ "$#" -eq 2 ]
then
	nc $2 -p 54321
fi
